require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/campus", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Campu. As you add validations to Campu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Campu.create! valid_attributes
      get campus_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      campu = Campu.create! valid_attributes
      get campu_url(campu)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_campu_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      campu = Campu.create! valid_attributes
      get edit_campu_url(campu)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Campu" do
        expect {
          post campus_url, params: { campu: valid_attributes }
        }.to change(Campu, :count).by(1)
      end

      it "redirects to the created campu" do
        post campus_url, params: { campu: valid_attributes }
        expect(response).to redirect_to(campu_url(Campu.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Campu" do
        expect {
          post campus_url, params: { campu: invalid_attributes }
        }.to change(Campu, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post campus_url, params: { campu: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested campu" do
        campu = Campu.create! valid_attributes
        patch campu_url(campu), params: { campu: new_attributes }
        campu.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the campu" do
        campu = Campu.create! valid_attributes
        patch campu_url(campu), params: { campu: new_attributes }
        campu.reload
        expect(response).to redirect_to(campu_url(campu))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        campu = Campu.create! valid_attributes
        patch campu_url(campu), params: { campu: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested campu" do
      campu = Campu.create! valid_attributes
      expect {
        delete campu_url(campu)
      }.to change(Campu, :count).by(-1)
    end

    it "redirects to the campus list" do
      campu = Campu.create! valid_attributes
      delete campu_url(campu)
      expect(response).to redirect_to(campus_url)
    end
  end
end
