require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/waypoints", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Waypoint. As you add validations to Waypoint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Waypoint.create! valid_attributes
      get waypoints_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      waypoint = Waypoint.create! valid_attributes
      get waypoint_url(waypoint)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_waypoint_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      waypoint = Waypoint.create! valid_attributes
      get edit_waypoint_url(waypoint)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Waypoint" do
        expect {
          post waypoints_url, params: { waypoint: valid_attributes }
        }.to change(Waypoint, :count).by(1)
      end

      it "redirects to the created waypoint" do
        post waypoints_url, params: { waypoint: valid_attributes }
        expect(response).to redirect_to(waypoint_url(Waypoint.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Waypoint" do
        expect {
          post waypoints_url, params: { waypoint: invalid_attributes }
        }.to change(Waypoint, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post waypoints_url, params: { waypoint: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested waypoint" do
        waypoint = Waypoint.create! valid_attributes
        patch waypoint_url(waypoint), params: { waypoint: new_attributes }
        waypoint.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the waypoint" do
        waypoint = Waypoint.create! valid_attributes
        patch waypoint_url(waypoint), params: { waypoint: new_attributes }
        waypoint.reload
        expect(response).to redirect_to(waypoint_url(waypoint))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        waypoint = Waypoint.create! valid_attributes
        patch waypoint_url(waypoint), params: { waypoint: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested waypoint" do
      waypoint = Waypoint.create! valid_attributes
      expect {
        delete waypoint_url(waypoint)
      }.to change(Waypoint, :count).by(-1)
    end

    it "redirects to the waypoints list" do
      waypoint = Waypoint.create! valid_attributes
      delete waypoint_url(waypoint)
      expect(response).to redirect_to(waypoints_url)
    end
  end
end
