default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vagrant
  #username: vagrant
  #password: vagrant
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: atividade_pratica_test

production:
  <<: *default
  database: atividade_pratica_production
  username: atividade_pratica
  password: <%= ENV['ATIVIDADE_PRATICA_DATABASE_PASSWORD'] %>
