test:
  issuer: 'test'
  secret: 'test'
  identifier: 'test'

development:
  issuer: 'https://app.homologacao.uff.br/auth/realms/master'
  secret: '13899e71-b668-4146-a20f-b07834a4feda'
  identifier: 'client-app2'